import https from "https";
import * as cheerio from "cheerio";
import {writeFile} from 'fs/promises'; // <-- promises


class PeppolCodeMetaData {
    title;
    fileName;
    identifier;
    version;
    url;
    enumChain;
    prefix;
}

async function loadMetadata(url, prefix, fileName) {
    try {
        const pageData = await fetchHTML(url);
        const $ = cheerio.load(pageData);
        const codeMetadata = new PeppolCodeMetaData;
        codeMetadata.url = url;
        codeMetadata.prefix = prefix;
        codeMetadata.fileName = fileName;
        codeMetadata.title = $('h1').text().trim();
        codeMetadata.identifier = $('dd:eq(0)').text().trim();
        codeMetadata.version = $('dd:eq(2)').text().trim();
        codeMetadata.enumChain = "";

        const divs = $('dd:last div');
        let needMethods = false;
        divs.each((index, element) => {
            const div = $(element);
            const strongText = div.find('strong').text().trim();
            const codeText = div.find('code').text().trim();

            codeMetadata.enumChain += `  /** ${strongText} */\n`;

            if (prefix) {
                needMethods = true;
                codeMetadata.enumChain += `  ${prefix}_${codeText.replaceAll("-", "_")}("${codeText}")${index === divs.length - 1 ? ';' : ','}\n`;
            } else {
                if (codeText.includes("-")) {
                    needMethods = true;

                    codeMetadata.enumChain += `  ${codeText.replaceAll("-", "_")}("${codeText}")${index === divs.length - 1 ? ';' : ','}\n`;
                } else {
                    codeMetadata.enumChain += `  ${codeText}${index === divs.length - 1 ? ';' : ','}\n`;
                }
            }
        });

        if (needMethods) {
            codeMetadata.enumChain += "\n";
            codeMetadata.enumChain +=
                "  private final String code;\n\n" +
                `  ${codeMetadata.fileName}(String code) {\n` +
                "    this.code = code;\n" +
                "  }\n\n" +
                "  public String getCode() {\n" +
                "    return code;\n" +
                "  }\n\n" +
                `  public static ${codeMetadata.fileName} fromCode(String code) {\n` +
                `    for (${codeMetadata.fileName} ve : values()) {\n` +
                "      if (ve.code.equals(code)) {\n" +
                "        return ve;\n" +
                "      }\n" +
                "    }\n" +
                `    throw new IllegalArgumentException("No ${codeMetadata.fileName} with code " + code);\n` +
                "  }\n\n" +
                "  @Override\n" +
                "  public String toString() {\n" +
                "    return code;\n" +
                "  }";
        }

        return codeMetadata;

    } catch (err) {
        console.error("Erreur de chargement :", err);
    }
}

async function writeMetaData(codeMetaData) {
    let enumClassContent = `package peppol.bis.invoice3.domain.codes;\n\n`;
    enumClassContent += `/**\n` +
        ` * ${codeMetaData.title}\n` +
        ` * ${codeMetaData.identifier}\n` +
        ` * ${codeMetaData.version}\n` +
        ` * ${codeMetaData.url}\n` +
        " *\n" +
        " * @author Jonathan Cambier (generated by node code loadEnumCode.js)\n" +
        " */\n";

    enumClassContent += `public enum ${codeMetaData.fileName} {\n` +
        codeMetaData.enumChain +
        "\n}\n";

    try {
        await writeFile(
            `./domain/src/main/java/peppol/bis/invoice3/domain/codes/${codeMetaData.fileName}.java`,
            enumClassContent,
            'utf8'
        );
        console.log("Fichier écrit !");
    } catch (err) {
        console.error(err);
    }
}

function fetchHTML(url) {
    return new Promise((resolve, reject) => {
        https.get(url, res => {
            if (res.statusCode !== 200) {
                reject(new Error(`HTTP ${res.statusCode}`));
                res.resume();
                return;
            }

            let data = "";
            res.on("data", chunk => data += chunk);
            res.on("end", () => resolve(data));
        }).on("error", reject);
    });
}


let creditNoteTypeCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-cn/",
    "CN",
    "CreditNoteTypeCode"
);
await writeMetaData(creditNoteTypeCode);

let currencyIdCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/ISO4217/",
    null,
    "CurrencyIdCode"
);
await writeMetaData(currencyIdCode);

let ElectronicAddressScheme = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/eas/",
    "EAS",
    "ElectronicAddressScheme"
);
await writeMetaData(ElectronicAddressScheme);

let InvoiceTypeCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-inv/",
    "INV",
    "InvoiceTypeCode"
);
await writeMetaData(InvoiceTypeCode);

let ItemTypeIdentificationCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL7143/",
    null,
    "ItemTypeIdentificationCode"
);
await writeMetaData(ItemTypeIdentificationCode);

let TaxCategoryIdentifier = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/",
    null,
    "TaxCategoryIdentifier"
);
await writeMetaData(TaxCategoryIdentifier);


let TaxExemptionReasonCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/",
    null,
    "TaxExemptionReasonCode"
);
await writeMetaData(TaxExemptionReasonCode);

let UnitIdCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNECERec20/",
    "X",
    "UnitIdCode"
);
await writeMetaData(UnitIdCode);

let VatDateCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNECERec20/",
    "VDC",
    "VatDateCode"
);
await writeMetaData(VatDateCode);

let PaymentMeansCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4461/",
    "PMC",
    "PaymentMeansCode"
);
await writeMetaData(PaymentMeansCode);

let AllowanceReasonCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5189/",
    "ARC",
    "AllowanceReasonCodes"
);
await writeMetaData(AllowanceReasonCode);

let ChargeReasonCode = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL7161/",
    null,
    "ChargeReasonCode"
);
await writeMetaData(ChargeReasonCode);

let SEPAIndicator = await loadMetadata(
    "https://docs.peppol.eu/poacc/billing/3.0/codelist/SEPA/",
    null,
    "SEPAIndicator"
);
await writeMetaData(SEPAIndicator);

