package peppol.bis.invoice3.domain.codes;

/**
 * Allowance reason codes (UNCL5189 subset)
 * UNCL5189
 * D.16B
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5189/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum AllowanceReasonCodes {
  /** Bonus for works ahead of schedule */
  ARC_41("41"),
  /** Other bonus */
  ARC_42("42"),
  /** Manufacturer’s consumer discount */
  ARC_60("60"),
  /** Due to military status */
  ARC_62("62"),
  /** Due to work accident */
  ARC_63("63"),
  /** Special agreement */
  ARC_64("64"),
  /** Production error discount */
  ARC_65("65"),
  /** New outlet discount */
  ARC_66("66"),
  /** Sample discount */
  ARC_67("67"),
  /** End-of-range discount */
  ARC_68("68"),
  /** Incoterm discount */
  ARC_70("70"),
  /** Point of sales threshold allowance */
  ARC_71("71"),
  /** Material surcharge/deduction */
  ARC_88("88"),
  /** Discount */
  ARC_95("95"),
  /** Special rebate */
  ARC_100("100"),
  /** Fixed long term */
  ARC_102("102"),
  /** Temporary */
  ARC_103("103"),
  /** Standard */
  ARC_104("104"),
  /** Yearly turnover */
  ARC_105("105");

  private final String code;

  AllowanceReasonCodes(String code) {
    this.code = code;
  }

  public String getCode() {
    return code;
  }

  public static AllowanceReasonCodes fromCode(String code) {
    for (AllowanceReasonCodes ve : values()) {
      if (ve.code.equals(code)) {
        return ve;
      }
    }
    throw new IllegalArgumentException("No AllowanceReasonCodes with code " + code);
  }

  @Override
  public String toString() {
    return code;
  }
}
