package peppol.bis.invoice3.domain.codes;

/**
 * Charge reason code (UNCL7161)
 * UNCL7161
 * D.16B
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL7161/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum ChargeReasonCode implements PeppolCode {
  /** Advertising */
  AA("AA"),
  /** Telecommunication */
  AAA("AAA"),
  /** Technical modification */
  AAC("AAC"),
  /** Job-order production */
  AAD("AAD"),
  /** Outlays */
  AAE("AAE"),
  /** Off-premises */
  AAF("AAF"),
  /** Additional processing */
  AAH("AAH"),
  /** Attesting */
  AAI("AAI"),
  /** Acceptance */
  AAS("AAS"),
  /** Rush delivery */
  AAT("AAT"),
  /** Special construction */
  AAV("AAV"),
  /** Airport facilities */
  AAY("AAY"),
  /** Concession */
  AAZ("AAZ"),
  /** Compulsory storage */
  ABA("ABA"),
  /** Fuel removal */
  ABB("ABB"),
  /** Into plane */
  ABC("ABC"),
  /** Overtime */
  ABD("ABD"),
  /** Tooling */
  ABF("ABF"),
  /** Miscellaneous */
  ABK("ABK"),
  /** Additional packaging */
  ABL("ABL"),
  /** Dunnage */
  ABN("ABN"),
  /** Containerisation */
  ABR("ABR"),
  /** Carton packing */
  ABS("ABS"),
  /** Hessian wrapped */
  ABT("ABT"),
  /** Polyethylene wrap packing */
  ABU("ABU"),
  /** Miscellaneous treatment */
  ACF("ACF"),
  /** Enamelling treatment */
  ACG("ACG"),
  /** Heat treatment */
  ACH("ACH"),
  /** Plating treatment */
  ACI("ACI"),
  /** Painting */
  ACJ("ACJ"),
  /** Polishing */
  ACK("ACK"),
  /** Priming */
  ACL("ACL"),
  /** Preservation treatment */
  ACM("ACM"),
  /** Fitting */
  ACS("ACS"),
  /** Consolidation */
  ADC("ADC"),
  /** Bill of lading */
  ADE("ADE"),
  /** Airbag */
  ADJ("ADJ"),
  /** Transfer */
  ADK("ADK"),
  /** Slipsheet */
  ADL("ADL"),
  /** Binding */
  ADM("ADM"),
  /** Repair or replacement of broken returnable package */
  ADN("ADN"),
  /** Efficient logistics */
  ADO("ADO"),
  /** Merchandising */
  ADP("ADP"),
  /** Product mix */
  ADQ("ADQ"),
  /** Other services */
  ADR("ADR"),
  /** Pick-up */
  ADT("ADT"),
  /** Chronic illness */
  ADW("ADW"),
  /** New product introduction */
  ADY("ADY"),
  /** Direct delivery */
  ADZ("ADZ"),
  /** Diversion */
  AEA("AEA"),
  /** Disconnect */
  AEB("AEB"),
  /** Distribution */
  AEC("AEC"),
  /** Handling of hazardous cargo */
  AED("AED"),
  /** Rents and leases */
  AEF("AEF"),
  /** Location differential */
  AEH("AEH"),
  /** Aircraft refueling */
  AEI("AEI"),
  /** Fuel shipped into storage */
  AEJ("AEJ"),
  /** Cash on delivery */
  AEK("AEK"),
  /** Small order processing service */
  AEL("AEL"),
  /** Clerical or administrative services */
  AEM("AEM"),
  /** Guarantee */
  AEN("AEN"),
  /** Collection and recycling */
  AEO("AEO"),
  /** Copyright fee collection */
  AEP("AEP"),
  /** Veterinary inspection service */
  AES("AES"),
  /** Pensioner service */
  AET("AET"),
  /** Medicine free pass holder */
  AEU("AEU"),
  /** Environmental protection service */
  AEV("AEV"),
  /** Environmental clean-up service */
  AEW("AEW"),
  /** National cheque processing service outside account area */
  AEX("AEX"),
  /** National payment service outside account area */
  AEY("AEY"),
  /** National payment service within account area */
  AEZ("AEZ"),
  /** Adjustments */
  AJ("AJ"),
  /** Authentication */
  AU("AU"),
  /** Cataloguing */
  CA("CA"),
  /** Cartage */
  CAB("CAB"),
  /** Certification */
  CAD("CAD"),
  /** Certificate of conformance */
  CAE("CAE"),
  /** Certificate of origin */
  CAF("CAF"),
  /** Cutting */
  CAI("CAI"),
  /** Consular service */
  CAJ("CAJ"),
  /** Customer collection */
  CAK("CAK"),
  /** Payroll payment service */
  CAL("CAL"),
  /** Cash transportation */
  CAM("CAM"),
  /** Home banking service */
  CAN("CAN"),
  /** Bilateral agreement service */
  CAO("CAO"),
  /** Insurance brokerage service */
  CAP("CAP"),
  /** Cheque generation */
  CAQ("CAQ"),
  /** Preferential merchandising location */
  CAR("CAR"),
  /** Crane */
  CAS("CAS"),
  /** Special colour service */
  CAT("CAT"),
  /** Sorting */
  CAU("CAU"),
  /** Battery collection and recycling */
  CAV("CAV"),
  /** Product take back fee */
  CAW("CAW"),
  /** Quality control released */
  CAX("CAX"),
  /** Quality control held */
  CAY("CAY"),
  /** Quality control embargo */
  CAZ("CAZ"),
  /** Car loading */
  CD("CD"),
  /** Cleaning */
  CG("CG"),
  /** Cigarette stamping */
  CS("CS"),
  /** Count and recount */
  CT("CT"),
  /** Layout/design */
  DAB("DAB"),
  /** Assortment allowance */
  DAC("DAC"),
  /** Driver assigned unloading */
  DAD("DAD"),
  /** Debtor bound */
  DAF("DAF"),
  /** Dealer allowance */
  DAG("DAG"),
  /** Allowance transferable to the consumer */
  DAH("DAH"),
  /** Growth of business */
  DAI("DAI"),
  /** Introduction allowance */
  DAJ("DAJ"),
  /** Multi-buy promotion */
  DAK("DAK"),
  /** Partnership */
  DAL("DAL"),
  /** Return handling */
  DAM("DAM"),
  /** Minimum order not fulfilled charge */
  DAN("DAN"),
  /** Point of sales threshold allowance */
  DAO("DAO"),
  /** Wholesaling discount */
  DAP("DAP"),
  /** Documentary credits transfer commission */
  DAQ("DAQ"),
  /** Delivery */
  DL("DL"),
  /** Engraving */
  EG("EG"),
  /** Expediting */
  EP("EP"),
  /** Exchange rate guarantee */
  ER("ER"),
  /** Fabrication */
  FAA("FAA"),
  /** Freight equalization */
  FAB("FAB"),
  /** Freight extraordinary handling */
  FAC("FAC"),
  /** Freight service */
  FC("FC"),
  /** Filling/handling */
  FH("FH"),
  /** Financing */
  FI("FI"),
  /** Grinding */
  GAA("GAA"),
  /** Hose */
  HAA("HAA"),
  /** Handling */
  HD("HD"),
  /** Hoisting and hauling */
  HH("HH"),
  /** Installation */
  IAA("IAA"),
  /** Installation and warranty */
  IAB("IAB"),
  /** Inside delivery */
  ID("ID"),
  /** Inspection */
  IF("IF"),
  /** Installation and training */
  IR("IR"),
  /** Invoicing */
  IS("IS"),
  /** Koshering */
  KO("KO"),
  /** Carrier count */
  L1("L1"),
  /** Labelling */
  LA("LA"),
  /** Labour */
  LAA("LAA"),
  /** Repair and return */
  LAB("LAB"),
  /** Legalisation */
  LF("LF"),
  /** Mounting */
  MAE("MAE"),
  /** Mail invoice */
  MI("MI"),
  /** Mail invoice to each location */
  ML("ML"),
  /** Non-returnable containers */
  NAA("NAA"),
  /** Outside cable connectors */
  OA("OA"),
  /** Invoice with shipment */
  PA("PA"),
  /** Phosphatizing (steel treatment) */
  PAA("PAA"),
  /** Packing */
  PC("PC"),
  /** Palletizing */
  PL("PL"),
  /** Price variation */
  PRV("PRV"),
  /** Repacking */
  RAB("RAB"),
  /** Repair */
  RAC("RAC"),
  /** Returnable container */
  RAD("RAD"),
  /** Restocking */
  RAF("RAF"),
  /** Re-delivery */
  RE("RE"),
  /** Refurbishing */
  RF("RF"),
  /** Rail wagon hire */
  RH("RH"),
  /** Loading */
  RV("RV"),
  /** Salvaging */
  SA("SA"),
  /** Shipping and handling */
  SAA("SAA"),
  /** Special packaging */
  SAD("SAD"),
  /** Stamping */
  SAE("SAE"),
  /** Consignee unload */
  SAI("SAI"),
  /** Shrink-wrap */
  SG("SG"),
  /** Special handling */
  SH("SH"),
  /** Special finish */
  SM("SM"),
  /** Set-up */
  SU("SU"),
  /** Tank renting */
  TAB("TAB"),
  /** Testing */
  TAC("TAC"),
  /** Transportation - third party billing */
  TT("TT"),
  /** Transportation by vendor */
  TV("TV"),
  /** Drop yard */
  V1("V1"),
  /** Drop dock */
  V2("V2"),
  /** Warehousing */
  WH("WH"),
  /** Combine all same day shipment */
  XAA("XAA"),
  /** Split pick-up */
  YY("YY"),
  /** Mutually defined */
  ZZZ("ZZZ");

  private final String code;

  ChargeReasonCode(String code) {
    this.code = code;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
