package peppol.bis.invoice3.domain.codes;

/**
 * Credit note type code (UNCL1001 subset)
 * UNCL1001-cn
 * D.16B
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-cn/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum CreditNoteTypeCode implements PeppolCode {
  /** Credit note related to goods or services */
  CN_81("81"),
  /** Credit note related to financial adjustments */
  CN_83("83"),
  /** Credit note */
  CN_381("381"),
  /** Factored credit note */
  CN_396("396"),
  /** Forwarder's credit note */
  CN_532("532");

  private final String code;

  CreditNoteTypeCode(String code) {
    this.code = code;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
