package peppol.bis.invoice3.domain.codes;

/**
 * Invoice type code (UNCL1001 subset)
 * UNCL1001-inv
 * D.16B
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-inv/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum InvoiceTypeCode implements PeppolCode {
  /** Request for payment */
  INV_71("71"),
  /** Debit note related to goods or services */
  INV_80("80"),
  /** Metered services invoice */
  INV_82("82"),
  /** Debit note related to financial adjustments */
  INV_84("84"),
  /** Tax notification */
  INV_102("102"),
  /** Final payment request based on completion of work */
  INV_218("218"),
  /** Payment request for completed units */
  INV_219("219"),
  /** Partial invoice */
  INV_326("326"),
  /** Commercial invoice which includes a packing list */
  INV_331("331"),
  /** Commercial invoice */
  INV_380("380"),
  /** Commission note */
  INV_382("382"),
  /** Debit note */
  INV_383("383"),
  /** Corrected invoice */
  INV_384("384"),
  /** Prepayment invoice */
  INV_386("386"),
  /** Tax invoice */
  INV_388("388"),
  /** Self-billed invoice */
  INV_389("389"),
  /** Factored invoice */
  INV_393("393"),
  /** Consignment invoice */
  INV_395("395"),
  /** Forwarder's invoice discrepancy report */
  INV_553("553"),
  /** Insurer's invoice */
  INV_575("575"),
  /** Forwarder's invoice */
  INV_623("623"),
  /** Freight invoice */
  INV_780("780"),
  /** Claim notification */
  INV_817("817"),
  /** Consular invoice */
  INV_870("870"),
  /** Partial construction invoice */
  INV_875("875"),
  /** Partial final construction invoice */
  INV_876("876"),
  /** Final construction invoice */
  INV_877("877");

  private final String code;

  InvoiceTypeCode(String code) {
    this.code = code;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
