package peppol.bis.invoice3.domain.codes;

/**
 * Item type identification code (UNCL7143)
 * UNCL7143
 * D.19A
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL7143/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum ItemTypeIdentificationCode implements PeppolCode {
  /** Product version number */
  AA("AA"),
  /** Assembly */
  AB("AB"),
  /** HIBC (Health Industry Bar Code) */
  AC("AC"),
  /** Cold roll number */
  AD("AD"),
  /** Hot roll number */
  AE("AE"),
  /** Slab number */
  AF("AF"),
  /** Software revision number */
  AG("AG"),
  /** UPC (Universal Product Code) Consumer package code (1-5-5) */
  AH("AH"),
  /** UPC (Universal Product Code) Consumer package code (1-5-5-1) */
  AI("AI"),
  /** Sample number */
  AJ("AJ"),
  /** Pack number */
  AK("AK"),
  /** UPC (Universal Product Code) Shipping container code (1-2-5-5) */
  AL("AL"),
  /** UPC (Universal Product Code)/EAN (European article number) Shipping container code (1-2-5-5-1) */
  AM("AM"),
  /** UPC (Universal Product Code) suffix */
  AN("AN"),
  /** State label code */
  AO("AO"),
  /** Heat number */
  AP("AP"),
  /** Coupon number */
  AQ("AQ"),
  /** Resource number */
  AR("AR"),
  /** Work task number */
  AS("AS"),
  /** Price look up number */
  AT("AT"),
  /** NSN (North Atlantic Treaty Organization Stock Number) */
  AU("AU"),
  /** Refined product code */
  AV("AV"),
  /** Exhibit */
  AW("AW"),
  /** End item */
  AX("AX"),
  /** Federal supply classification */
  AY("AY"),
  /** Engineering data list */
  AZ("AZ"),
  /** Milestone event number */
  BA("BA"),
  /** Lot number */
  BB("BB"),
  /** National drug code 4-4-2 format */
  BC("BC"),
  /** National drug code 5-3-2 format */
  BD("BD"),
  /** National drug code 5-4-1 format */
  BE("BE"),
  /** National drug code 5-4-2 format */
  BF("BF"),
  /** National drug code */
  BG("BG"),
  /** Part number */
  BH("BH"),
  /** Local Stock Number (LSN) */
  BI("BI"),
  /** Next higher assembly number */
  BJ("BJ"),
  /** Data category */
  BK("BK"),
  /** Control number */
  BL("BL"),
  /** Special material identification code */
  BM("BM"),
  /** Locally assigned control number */
  BN("BN"),
  /** Buyer's colour */
  BO("BO"),
  /** Buyer's part number */
  BP("BP"),
  /** Variable measure product code */
  BQ("BQ"),
  /** Financial phase */
  BR("BR"),
  /** Contract breakdown */
  BS("BS"),
  /** Technical phase */
  BT("BT"),
  /** Dye lot number */
  BU("BU"),
  /** Daily statement of activities */
  BV("BV"),
  /** Periodical statement of activities within a bilaterally agreed time period */
  BW("BW"),
  /** Calendar week statement of activities */
  BX("BX"),
  /** Calendar month statement of activities */
  BY("BY"),
  /** Original equipment number */
  BZ("BZ"),
  /** Industry commodity code */
  CC("CC"),
  /** Commodity grouping */
  CG("CG"),
  /** Colour number */
  CL("CL"),
  /** Contract number */
  CR("CR"),
  /** Customs article number */
  CV("CV"),
  /** Drawing revision number */
  DR("DR"),
  /** Drawing */
  DW("DW"),
  /** Engineering change level */
  EC("EC"),
  /** Material code */
  EF("EF"),
  /** EMDN (European Medical Device Nomenclature) */
  EMD("EMD"),
  /** International Article Numbering Association (EAN) */
  EN("EN"),
  /** Fish species */
  FS("FS"),
  /** Buyer's internal product group code */
  GB("GB"),
  /** Global model number */
  GMN("GMN"),
  /** National product group code */
  GN("GN"),
  /** General specification number */
  GS("GS"),
  /** Harmonised system */
  HS("HS"),
  /** ISBN (International Standard Book Number) */
  IB("IB"),
  /** Buyer's item number */
  IN("IN"),
  /** ISSN (International Standard Serial Number) */
  IS("IS"),
  /** Buyer's style number */
  IT("IT"),
  /** Buyer's size code */
  IZ("IZ"),
  /** Machine number */
  MA("MA"),
  /** Manufacturer's (producer's) article number */
  MF("MF"),
  /** Model number */
  MN("MN"),
  /** Product/service identification number */
  MP("MP"),
  /** Batch number */
  NB("NB"),
  /** Customer order number */
  ON("ON"),
  /** Part number description */
  PD("PD"),
  /** Purchaser's order line number */
  PL("PL"),
  /** Purchase order number */
  PO("PO"),
  /** Promotional variant number */
  PV("PV"),
  /** Buyer's qualifier for size */
  QS("QS"),
  /** Returnable container number */
  RC("RC"),
  /** Release number */
  RN("RN"),
  /** Run number */
  RU("RU"),
  /** Record keeping of model year */
  RY("RY"),
  /** Supplier's article number */
  SA("SA"),
  /** Standard group of products (mixed assortment) */
  SG("SG"),
  /** SKU (Stock keeping unit) */
  SK("SK"),
  /** Serial number */
  SN("SN"),
  /** RSK number */
  SRS("SRS"),
  /** IFLS (Institut Francais du Libre Service) 5 digit product classification code */
  SRT("SRT"),
  /** IFLS (Institut Francais du Libre Service) 9 digit product classification code */
  SRU("SRU"),
  /** GS1 Global Trade Item Number */
  SRV("SRV"),
  /** EDIS (Energy Data Identification System) */
  SRW("SRW"),
  /** Slaughter number */
  SRX("SRX"),
  /** Official animal number */
  SRY("SRY"),
  /** Harmonized tariff schedule */
  SRZ("SRZ"),
  /** Supplier's supplier article number */
  SS("SS"),
  /** 46 Level DOT Code */
  SSA("SSA"),
  /** Airline Tariff 6D */
  SSB("SSB"),
  /** Title 49 Code of Federal Regulations */
  SSC("SSC"),
  /** International Civil Aviation Administration code */
  SSD("SSD"),
  /** Hazardous Materials ID DOT */
  SSE("SSE"),
  /** Endorsement */
  SSF("SSF"),
  /** Air Force Regulation 71-4 */
  SSG("SSG"),
  /** Breed */
  SSH("SSH"),
  /** Chemical Abstract Service (CAS) registry number */
  SSI("SSI"),
  /** Engine model designation */
  SSJ("SSJ"),
  /** Institutional Meat Purchase Specifications (IMPS) Number */
  SSK("SSK"),
  /** Price Look-Up code (PLU) */
  SSL("SSL"),
  /** International Maritime Organization (IMO) Code */
  SSM("SSM"),
  /** Bureau of Explosives 600-A (rail) */
  SSN("SSN"),
  /** United Nations Dangerous Goods List */
  SSO("SSO"),
  /** International Code of Botanical Nomenclature (ICBN) */
  SSP("SSP"),
  /** International Code of Zoological Nomenclature (ICZN) */
  SSQ("SSQ"),
  /** International Code of Nomenclature for Cultivated Plants (ICNCP) */
  SSR("SSR"),
  /** Distributor’s article identifier */
  SSS("SSS"),
  /** Norwegian Classification system ENVA */
  SST("SST"),
  /** Supplier assigned classification */
  SSU("SSU"),
  /** Mexican classification system AMECE */
  SSV("SSV"),
  /** German classification system CCG */
  SSW("SSW"),
  /** Finnish classification system EANFIN */
  SSX("SSX"),
  /** Canadian classification system ICC */
  SSY("SSY"),
  /** French classification system IFLS5 */
  SSZ("SSZ"),
  /** Style number */
  ST("ST"),
  /** Dutch classification system CBL */
  STA("STA"),
  /** Japanese classification system JICFS */
  STB("STB"),
  /** European Union dairy subsidy eligibility classification */
  STC("STC"),
  /** GS1 Spain classification system */
  STD("STD"),
  /** GS1 Poland classification system */
  STE("STE"),
  /** Federal Agency on Technical Regulating and Metrology of the Russian Federation */
  STF("STF"),
  /** Efficient Consumer Response (ECR) Austria classification system */
  STG("STG"),
  /** GS1 Italy classification system */
  STH("STH"),
  /** CPV (Common Procurement Vocabulary) */
  STI("STI"),
  /** IFDA (International Foodservice Distributors Association) */
  STJ("STJ"),
  /** AHFS (American Hospital Formulary Service) pharmacologic -therapeutic classification */
  STK("STK"),
  /** ATC (Anatomical Therapeutic Chemical) classification system */
  STL("STL"),
  /** CLADIMED (Classification des Dispositifs Médicaux) */
  STM("STM"),
  /** CMDR (Canadian Medical Device Regulations) classification system */
  STN("STN"),
  /** CNDM (Classificazione Nazionale dei Dispositivi Medici) */
  STO("STO"),
  /** UK DM&D (Dictionary of Medicines & Devices) standard coding scheme */
  STP("STP"),
  /** eCl@ss */
  STQ("STQ"),
  /** EDMA (European Diagnostic Manufacturers Association) Product Classification */
  STR("STR"),
  /** EGAR (European Generic Article Register) */
  STS("STS"),
  /** GMDN (Global Medical Devices Nomenclature) */
  STT("STT"),
  /** GPI (Generic Product Identifier) */
  STU("STU"),
  /** HCPCS (Healthcare Common Procedure Coding System) */
  STV("STV"),
  /** ICPS (International Classification for Patient Safety) */
  STW("STW"),
  /** MedDRA (Medical Dictionary for Regulatory Activities) */
  STX("STX"),
  /** Medical Columbus */
  STY("STY"),
  /** NAPCS (North American Product Classification System) */
  STZ("STZ"),
  /** NHS (National Health Services) eClass */
  SUA("SUA"),
  /** US FDA (Food and Drug Administration) Product Code Classification Database */
  SUB("SUB"),
  /** SNOMED CT (Systematized Nomenclature of Medicine-Clinical Terms) */
  SUC("SUC"),
  /** UMDNS (Universal Medical Device Nomenclature System) */
  SUD("SUD"),
  /** GS1 Global Returnable Asset Identifier, non-serialised */
  SUE("SUE"),
  /** IMEI */
  SUF("SUF"),
  /** Waste Type (EMSA) */
  SUG("SUG"),
  /** Ship's store classification type */
  SUH("SUH"),
  /** Emergency fire code */
  SUI("SUI"),
  /** Emergency spillage code */
  SUJ("SUJ"),
  /** IMDG packing group */
  SUK("SUK"),
  /** MARPOL Code IBC */
  SUL("SUL"),
  /** IMDG subsidiary risk class */
  SUM("SUM"),
  /** Transport group number */
  TG("TG"),
  /** Taxonomic Serial Number */
  TSN("TSN"),
  /** IMDG main hazard class */
  TSO("TSO"),
  /** EU Combined Nomenclature */
  TSP("TSP"),
  /** Therapeutic classification number */
  TSQ("TSQ"),
  /** European Waste Catalogue */
  TSR("TSR"),
  /** Price grouping code */
  TSS("TSS"),
  /** UNSPSC */
  TST("TST"),
  /** EU RoHS Directive */
  TSU("TSU"),
  /** Ultimate customer's article number */
  UA("UA"),
  /** UPC (Universal product code) */
  UP("UP"),
  /** Vendor item number */
  VN("VN"),
  /** Vendor's (seller's) part number */
  VP("VP"),
  /** Vendor's supplemental item number */
  VS("VS"),
  /** Vendor specification number */
  VX("VX"),
  /** Mutually defined */
  ZZZ("ZZZ"),
  /** Phytosanitary Passport identifier */
  PPI("PPI");

  private final String code;

  ItemTypeIdentificationCode(String code) {
    this.code = code;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
