package peppol.bis.invoice3.domain.codes;

/**
 * Mime code (subset of IANA code list)
 * MimeCode
 * 1.0
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/MimeCode/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum MimeCode implements PeppolCode {
  /** text/csv */
  CSV("text/csv"),
  /** application/pdf */
  PDF("application/pdf"),
  /** image/png */
  PNG("image/png"),
  /** image/jpeg */
  JPEG("image/jpeg"),
  /** application/vnd.openxmlformats-officedocument.spreadsheetml.sheet */
  SHEET("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  /** application/vnd.oasis.opendocument.spreadsheet */
  SPREADSHEET("application/vnd.oasis.opendocument.spreadsheet");

  private final String code;

  MimeCode(String code) {
    this.code = code;
  }

  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
