package peppol.bis.invoice3.domain.codes;

/**
 * Payment means code (UNCL4461)
 * UNCL4461
 * D.16B
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4461/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum PaymentMeansPeppolCode implements PeppolCode {
  /** Instrument not defined */
  PMC_1("1"),
  /** Automated clearing house credit */
  PMC_2("2"),
  /** Automated clearing house debit */
  PMC_3("3"),
  /** ACH demand debit reversal */
  PMC_4("4"),
  /** ACH demand credit reversal */
  PMC_5("5"),
  /** ACH demand credit */
  PMC_6("6"),
  /** ACH demand debit */
  PMC_7("7"),
  /** Hold */
  PMC_8("8"),
  /** National or regional clearing */
  PMC_9("9"),
  /** In cash */
  PMC_10("10"),
  /** ACH savings credit reversal */
  PMC_11("11"),
  /** ACH savings debit reversal */
  PMC_12("12"),
  /** ACH savings credit */
  PMC_13("13"),
  /** ACH savings debit */
  PMC_14("14"),
  /** Bookentry credit */
  PMC_15("15"),
  /** Bookentry debit */
  PMC_16("16"),
  /** ACH demand cash concentration/disbursement (CCD) credit */
  PMC_17("17"),
  /** ACH demand cash concentration/disbursement (CCD) debit */
  PMC_18("18"),
  /** ACH demand corporate trade payment (CTP) credit */
  PMC_19("19"),
  /** Cheque */
  PMC_20("20"),
  /** Banker's draft */
  PMC_21("21"),
  /** Certified banker's draft */
  PMC_22("22"),
  /** Bank cheque (issued by a banking or similar establishment) */
  PMC_23("23"),
  /** Bill of exchange awaiting acceptance */
  PMC_24("24"),
  /** Certified cheque */
  PMC_25("25"),
  /** Local cheque */
  PMC_26("26"),
  /** ACH demand corporate trade payment (CTP) debit */
  PMC_27("27"),
  /** ACH demand corporate trade exchange (CTX) credit */
  PMC_28("28"),
  /** ACH demand corporate trade exchange (CTX) debit */
  PMC_29("29"),
  /** Credit transfer */
  PMC_30("30"),
  /** Debit transfer */
  PMC_31("31"),
  /** ACH demand cash concentration/disbursement plus (CCD+) credit */
  PMC_32("32"),
  /** ACH demand cash concentration/disbursement plus (CCD+) debit */
  PMC_33("33"),
  /** ACH prearranged payment and deposit (PPD) */
  PMC_34("34"),
  /** ACH savings cash concentration/disbursement (CCD) credit */
  PMC_35("35"),
  /** ACH savings cash concentration/disbursement (CCD) debit */
  PMC_36("36"),
  /** ACH savings corporate trade payment (CTP) credit */
  PMC_37("37"),
  /** ACH savings corporate trade payment (CTP) debit */
  PMC_38("38"),
  /** ACH savings corporate trade exchange (CTX) credit */
  PMC_39("39"),
  /** ACH savings corporate trade exchange (CTX) debit */
  PMC_40("40"),
  /** ACH savings cash concentration/disbursement plus (CCD+) credit */
  PMC_41("41"),
  /** Payment to bank account */
  PMC_42("42"),
  /** ACH savings cash concentration/disbursement plus (CCD+) debit */
  PMC_43("43"),
  /** Accepted bill of exchange */
  PMC_44("44"),
  /** Referenced home-banking credit transfer */
  PMC_45("45"),
  /** Interbank debit transfer */
  PMC_46("46"),
  /** Home-banking debit transfer */
  PMC_47("47"),
  /** Bank card */
  PMC_48("48"),
  /** Direct debit */
  PMC_49("49"),
  /** Payment by postgiro */
  PMC_50("50"),
  /** FR, norme 6 97-Telereglement CFONB (French Organisation for */
  PMC_51("51"),
  /** Urgent commercial payment */
  PMC_52("52"),
  /** Urgent Treasury Payment */
  PMC_53("53"),
  /** Credit card */
  PMC_54("54"),
  /** Debit card */
  PMC_55("55"),
  /** Bankgiro */
  PMC_56("56"),
  /** Standing agreement */
  PMC_57("57"),
  /** SEPA credit transfer */
  PMC_58("58"),
  /** SEPA direct debit */
  PMC_59("59"),
  /** Promissory note */
  PMC_60("60"),
  /** Promissory note signed by the debtor */
  PMC_61("61"),
  /** Promissory note signed by the debtor and endorsed by a bank */
  PMC_62("62"),
  /** Promissory note signed by the debtor and endorsed by a third party */
  PMC_63("63"),
  /** Promissory note signed by a bank */
  PMC_64("64"),
  /** Promissory note signed by a bank and endorsed by another bank */
  PMC_65("65"),
  /** Promissory note signed by a third party */
  PMC_66("66"),
  /** Promissory note signed by a third party and endorsed by a bank */
  PMC_67("67"),
  /** Online payment service */
  PMC_68("68"),
  /** Bill drawn by the creditor on the debtor */
  PMC_70("70"),
  /** Bill drawn by the creditor on a bank */
  PMC_74("74"),
  /** Bill drawn by the creditor, endorsed by another bank */
  PMC_75("75"),
  /** Bill drawn by the creditor on a bank and endorsed by a third party */
  PMC_76("76"),
  /** Bill drawn by the creditor on a third party */
  PMC_77("77"),
  /** Bill drawn by creditor on third party, accepted and endorsed by bank */
  PMC_78("78"),
  /** Not transferable banker's draft */
  PMC_91("91"),
  /** Not transferable local cheque */
  PMC_92("92"),
  /** Reference giro */
  PMC_93("93"),
  /** Urgent giro */
  PMC_94("94"),
  /** Free format giro */
  PMC_95("95"),
  /** Requested method for payment was not used */
  PMC_96("96"),
  /** Clearing between partners */
  PMC_97("97"),
  /** JP, Electronically Recorded Monetary Claims */
  PMC_98("98"),
  /** Mutually defined */
  PMC_ZZZ("ZZZ"),
  /** Transfer Advice */
  PMC_69("69");

  private final String code;

  PaymentMeansPeppolCode(String code) {
    this.code = code;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
