package peppol.bis.invoice3.domain.codes;

/**
 * SEPA indicator
 * SEPA
 * 1.0
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/SEPA/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum SEPAIndicator implements PeppolCode {
  /** SEPA unique bank assigned creditor identifier */
  SEPA("SEPA");

  private final String code;

  SEPAIndicator(String code) {
    this.code = code;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
