package peppol.bis.invoice3.domain.codes;

/**
 * SEPA indicator
 * SEPA
 * 1.0
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/SEPA/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum SEPAIndicator {
  /** SEPA unique bank assigned creditor identifier */
  SEPA;

}
