package peppol.bis.invoice3.domain.codes;

/**
 * Duty or tax or fee category code (Subset of UNCL5305)
 * UNCL5305
 * D.16B
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum TaxCategoryIdentifier {
  /** Vat Reverse Charge */
  AE,
  /** Exempt from Tax */
  E,
  /** Standard rate */
  S,
  /** Zero rated goods */
  Z,
  /** Free export item, VAT not charged */
  G,
  /** Services outside scope of tax */
  O,
  /** VAT exempt for EEA intra-community supply of goods and
            services */
  K,
  /** Canary Islands general indirect tax */
  L,
  /** Tax for production, services and importation in Ceuta and
            Melilla */
  M,
  /** Transferred (VAT), In Italy */
  B;

}
