package peppol.bis.invoice3.domain.codes;

/**
 * Duty or tax or fee category code (Subset of UNCL5305)
 * UNCL5305
 * D.16B
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum TaxCategoryIdentifier implements PeppolCode {
  /** Vat Reverse Charge */
  AE("AE"),
  /** Exempt from Tax */
  E("E"),
  /** Standard rate */
  S("S"),
  /** Zero rated goods */
  Z("Z"),
  /** Free export item, VAT not charged */
  G("G"),
  /** Services outside scope of tax */
  O("O"),
  /** VAT exempt for EEA intra-community supply of goods and
            services */
  K("K"),
  /** Canary Islands general indirect tax */
  L("L"),
  /** Tax for production, services and importation in Ceuta and
            Melilla */
  M("M"),
  /** Transferred (VAT), In Italy */
  B("B");

  private final String code;

  TaxCategoryIdentifier(String code) {
    this.code = code;
  }

  @Override
  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code;
  }
}
