package peppol.bis.invoice3.domain.codes;

/**
 * VATEX code list
 * vatex
 * 
 * https://docs.peppol.eu/poacc/billing/3.0/codelist/vatex/
 *
 * @author Jonathan Cambier (generated by node code loadEnumCode.js)
 */
public enum TaxExemptionReasonCode {
  /** Exempt based on article 79, point c of Council Directive 2006/112/EC */
  VATEX_EU_79_C("VATEX-EU-79-C"),
  /** Exempt based on article 132 of Council Directive 2006/112/EC */
  VATEX_EU_132("VATEX-EU-132"),
  /** Exempt based on article 132, section 1 (a) of Council Directive 2006/112/EC */
  VATEX_EU_132_1A("VATEX-EU-132-1A"),
  /** Exempt based on article 132, section 1 (b) of Council Directive 2006/112/EC */
  VATEX_EU_132_1B("VATEX-EU-132-1B"),
  /** Exempt based on article 132, section 1 (c) of Council Directive 2006/112/EC */
  VATEX_EU_132_1C("VATEX-EU-132-1C"),
  /** Exempt based on article 132, section 1 (d) of Council Directive 2006/112/EC */
  VATEX_EU_132_1D("VATEX-EU-132-1D"),
  /** Exempt based on article 132, section 1 (e) of Council Directive 2006/112/EC */
  VATEX_EU_132_1E("VATEX-EU-132-1E"),
  /** Exempt based on article 132, section 1 (f) of Council Directive 2006/112/EC */
  VATEX_EU_132_1F("VATEX-EU-132-1F"),
  /** Exempt based on article 132, section 1 (g) of Council Directive 2006/112/EC */
  VATEX_EU_132_1G("VATEX-EU-132-1G"),
  /** Exempt based on article 132, section 1 (h) of Council Directive 2006/112/EC */
  VATEX_EU_132_1H("VATEX-EU-132-1H"),
  /** Exempt based on article 132, section 1 (i) of Council Directive 2006/112/EC */
  VATEX_EU_132_1I("VATEX-EU-132-1I"),
  /** Exempt based on article 132, section 1 (j) of Council Directive 2006/112/EC */
  VATEX_EU_132_1J("VATEX-EU-132-1J"),
  /** Exempt based on article 132, section 1 (k) of Council Directive 2006/112/EC */
  VATEX_EU_132_1K("VATEX-EU-132-1K"),
  /** Exempt based on article 132, section 1 (l) of Council Directive 2006/112/EC */
  VATEX_EU_132_1L("VATEX-EU-132-1L"),
  /** Exempt based on article 132, section 1 (m) of Council Directive 2006/112/EC */
  VATEX_EU_132_1M("VATEX-EU-132-1M"),
  /** Exempt based on article 132, section 1 (n) of Council Directive 2006/112/EC */
  VATEX_EU_132_1N("VATEX-EU-132-1N"),
  /** Exempt based on article 132, section 1 (o) of Council Directive 2006/112/EC */
  VATEX_EU_132_1O("VATEX-EU-132-1O"),
  /** Exempt based on article 132, section 1 (p) of Council Directive 2006/112/EC */
  VATEX_EU_132_1P("VATEX-EU-132-1P"),
  /** Exempt based on article 132, section 1 (q) of Council Directive 2006/112/EC */
  VATEX_EU_132_1Q("VATEX-EU-132-1Q"),
  /** Exempt based on article 143 of Council Directive 2006/112/EC */
  VATEX_EU_143("VATEX-EU-143"),
  /** Exempt based on article 143, section 1 (a) of Council Directive 2006/112/EC */
  VATEX_EU_143_1A("VATEX-EU-143-1A"),
  /** Exempt based on article 143, section 1 (b) of Council Directive 2006/112/EC */
  VATEX_EU_143_1B("VATEX-EU-143-1B"),
  /** Exempt based on article 143, section 1 (c) of Council Directive 2006/112/EC */
  VATEX_EU_143_1C("VATEX-EU-143-1C"),
  /** Exempt based on article 143, section 1 (d) of Council Directive 2006/112/EC */
  VATEX_EU_143_1D("VATEX-EU-143-1D"),
  /** Exempt based on article 143, section 1 (e) of Council Directive 2006/112/EC */
  VATEX_EU_143_1E("VATEX-EU-143-1E"),
  /** Exempt based on article 143, section 1 (f) of Council Directive 2006/112/EC */
  VATEX_EU_143_1F("VATEX-EU-143-1F"),
  /** Exempt based on article 143, section 1 (fa) of Council Directive 2006/112/EC */
  VATEX_EU_143_1FA("VATEX-EU-143-1FA"),
  /** Exempt based on article 143, section 1 (g) of Council Directive 2006/112/EC */
  VATEX_EU_143_1G("VATEX-EU-143-1G"),
  /** Exempt based on article 143, section 1 (h) of Council Directive 2006/112/EC */
  VATEX_EU_143_1H("VATEX-EU-143-1H"),
  /** Exempt based on article 143, section 1 (i) of Council Directive 2006/112/EC */
  VATEX_EU_143_1I("VATEX-EU-143-1I"),
  /** Exempt based on article 143, section 1 (j) of Council Directive 2006/112/EC */
  VATEX_EU_143_1J("VATEX-EU-143-1J"),
  /** Exempt based on article 143, section 1 (k) of Council Directive 2006/112/EC */
  VATEX_EU_143_1K("VATEX-EU-143-1K"),
  /** Exempt based on article 143, section 1 (l) of Council Directive 2006/112/EC */
  VATEX_EU_143_1L("VATEX-EU-143-1L"),
  /** Exempt based on article 144 of Council Directive 2006/112/EC */
  VATEX_EU_144("VATEX-EU-144"),
  /** Exempt based on article 146 section 1 (e) of Council Directive 2006/112/EC */
  VATEX_EU_146_1E("VATEX-EU-146-1E"),
  /** Exempt based on article 148 of Council Directive 2006/112/EC */
  VATEX_EU_148("VATEX-EU-148"),
  /** Exempt based on article 148, section (a) of Council Directive 2006/112/EC */
  VATEX_EU_148_A("VATEX-EU-148-A"),
  /** Exempt based on article 148, section (b) of Council Directive 2006/112/EC */
  VATEX_EU_148_B("VATEX-EU-148-B"),
  /** Exempt based on article 148, section (c) of Council Directive 2006/112/EC */
  VATEX_EU_148_C("VATEX-EU-148-C"),
  /** Exempt based on article 148, section (d) of Council Directive 2006/112/EC */
  VATEX_EU_148_D("VATEX-EU-148-D"),
  /** Exempt based on article 148, section (e) of Council Directive 2006/112/EC */
  VATEX_EU_148_E("VATEX-EU-148-E"),
  /** Exempt based on article 148, section (f) of Council Directive 2006/112/EC */
  VATEX_EU_148_F("VATEX-EU-148-F"),
  /** Exempt based on article 148, section (g) of Council Directive 2006/112/EC */
  VATEX_EU_148_G("VATEX-EU-148-G"),
  /** Exempt based on article 151 of Council Directive 2006/112/EC */
  VATEX_EU_151("VATEX-EU-151"),
  /** Exempt based on article 151, section 1 (a) of Council Directive 2006/112/EC */
  VATEX_EU_151_1A("VATEX-EU-151-1A"),
  /** Exempt based on article 151, section 1 (aa) of Council Directive 2006/112/EC */
  VATEX_EU_151_1AA("VATEX-EU-151-1AA"),
  /** Exempt based on article 151, section 1 (b) of Council Directive 2006/112/EC */
  VATEX_EU_151_1B("VATEX-EU-151-1B"),
  /** Exempt based on article 151, section 1 (c) of Council Directive 2006/112/EC */
  VATEX_EU_151_1C("VATEX-EU-151-1C"),
  /** Exempt based on article 151, section 1 (d) of Council Directive 2006/112/EC */
  VATEX_EU_151_1D("VATEX-EU-151-1D"),
  /** Exempt based on article 151, section 1 (e) of Council Directive 2006/112/EC */
  VATEX_EU_151_1E("VATEX-EU-151-1E"),
  /** Exempt based on article 159 of Council Directive 2006/112/EC */
  VATEX_EU_159("VATEX-EU-159"),
  /** Exempt based on article 309 of Council Directive 2006/112/EC */
  VATEX_EU_309("VATEX-EU-309"),
  /** Reverse charge */
  VATEX_EU_AE("VATEX-EU-AE"),
  /** Intra-Community acquisition from second hand means of transport */
  VATEX_EU_D("VATEX-EU-D"),
  /** Intra-Community acquisition of second hand goods */
  VATEX_EU_F("VATEX-EU-F"),
  /** Export outside the EU */
  VATEX_EU_G("VATEX-EU-G"),
  /** Intra-Community acquisition of works of art */
  VATEX_EU_I("VATEX-EU-I"),
  /** Intra-Community supply */
  VATEX_EU_IC("VATEX-EU-IC"),
  /** Not subject to VAT */
  VATEX_EU_O("VATEX-EU-O"),
  /** Intra-Community acquisition of collectors items and antiques */
  VATEX_EU_J("VATEX-EU-J"),
  /** France domestic VAT franchise in base */
  VATEX_FR_FRANCHISE("VATEX-FR-FRANCHISE"),
  /** France domestic Credit Notes without VAT, due to supplier forfeit of VAT for discount */
  VATEX_FR_CNWVAT("VATEX-FR-CNWVAT"),
  /** Exempt based on article 153 of Council Directive 2006/112/EC */
  VATEX_EU_153("VATEX-EU-153"),
  /** Exempt based on 1 of article 261 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261_1("VATEX-FR-CGI261-1"),
  /** Exempt based on 2 of article 261 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261_2("VATEX-FR-CGI261-2"),
  /** Exempt based on 3 of article 261 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261_3("VATEX-FR-CGI261-3"),
  /** Exempt based on 4 of article 261 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261_4("VATEX-FR-CGI261-4"),
  /** Exempt based on 5 of article 261 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261_5("VATEX-FR-CGI261-5"),
  /** Exempt based on 7 of article 261 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261_7("VATEX-FR-CGI261-7"),
  /** Exempt based on 8 of article 261 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261_8("VATEX-FR-CGI261-8"),
  /** Exempt based on article 261 A of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261A("VATEX-FR-CGI261A"),
  /** Exempt based on article 261 B of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261B("VATEX-FR-CGI261B"),
  /** Exempt based on 1° of article 261 C of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261C_1("VATEX-FR-CGI261C-1"),
  /** Exempt based on 2° of article 261 C of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261C_2("VATEX-FR-CGI261C-2"),
  /** Exempt based on 3° of article 261 C of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261C_3("VATEX-FR-CGI261C-3"),
  /** Exempt based on 1° of article 261 D of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261D_1("VATEX-FR-CGI261D-1"),
  /** Exempt based on 1°bis of article 261 D of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261D_1BIS("VATEX-FR-CGI261D-1BIS"),
  /** Exempt based on 2° of article 261 D of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261D_2("VATEX-FR-CGI261D-2"),
  /** Exempt based on 3° of article 261 D of the Code Général des Impôts (CGI ; General tax code)
Exonération de TVA - Article 261 D-3° du Code Général des Impôts */
  VATEX_FR_CGI261D_3("VATEX-FR-CGI261D-3"),
  /** Exempt based on 4° of article 261 D of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261D_4("VATEX-FR-CGI261D-4"),
  /** Exempt based on 1° of article 261 E of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261E_1("VATEX-FR-CGI261E-1"),
  /** Exempt based on 2° of article 261 E of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI261E_2("VATEX-FR-CGI261E-2"),
  /** Exempt based on article 277 A of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI277A("VATEX-FR-CGI277A"),
  /** Exempt based on article 275 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI275("VATEX-FR-CGI275"),
  /** Exempt based on article 298 sexdecies A of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_298SEXDECIESA("VATEX-FR-298SEXDECIESA"),
  /** Exempt based on article 295 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_CGI295("VATEX-FR-CGI295"),
  /** Exempt based on 2 of article 283 of the Code Général des Impôts (CGI ; General tax code) */
  VATEX_FR_AE("VATEX-FR-AE");

  private final String code;

  TaxExemptionReasonCode(String code) {
    this.code = code;
  }

  public String getCode() {
    return code;
  }

  public static TaxExemptionReasonCode fromCode(String code) {
    for (TaxExemptionReasonCode ve : values()) {
      if (ve.code.equals(code)) {
        return ve;
      }
    }
    throw new IllegalArgumentException("No TaxExemptionReasonCode with code " + code);
  }

  @Override
  public String toString() {
    return code;
  }
}
